name: bmicalculater


description: simple application for applying statefull widget example

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  sqflite: ^2.0.3

environment:
  sdk: '>=2.10.0 <3.0.0'


flutter:
  uses-material-design: true


  assets: 
   - assets/images/